### ISSUE TITLE
how to evaluate the depth metrics？

### ISSUE THREAD

**Issue by Kammagod** [susaha/relate_depth_and_semantics_for_uda#1]
hi,
i want to evaluate the depth metrics
Can you help me？

**Comment by susaha** [comment]
Please refer to: https://github.com/sshan-zhao/GASDA/blob/3316e8b0dc6a51acbd89496e437da249352c1189/utils/dataset_util.py#L27

**Comment by Kammagod** [comment]
> Please refer to: https://github.com/sshan-zhao/GASDA/blob/3316e8b0dc6a51acbd89496e437da249352c1189/utils/dataset_util.py#L27

very very thank you！！！ but i cannot get your paper indicators, can you tell me how to get, and What is the max_depth value set to ? please !!!!

**Comment by Kammagod** [comment]
> Please refer to: https://github.com/sshan-zhao/GASDA/blob/3316e8b0dc6a51acbd89496e437da249352c1189/utils/dataset_util.py#L27

when i follow your work, to get the DADA depth map, i find it has a negative value, how do you deal with it to 
visualize DADA's depth map?  very very very thank you !!!!!!!!!!!

**Comment by susaha** [comment]
I discard all negative values.

**Comment by Kammagod** [comment]
> I discard all negative values.
very thank you!!!!! Wish you all the best!
